apiVersion: hive.openshift.io/v1alpha1
kind: SelectorSyncSet
metadata:
  generation: 1
  name: managed-prometheus-exporter-ebs-iops-reporter
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: "true"
  resourceApplyMode: sync